name: Schedule Edge Function

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the function every day at midnight UTC

jobs:
  run-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST https://lmmobnqmxkcdwdhhpwwd.supabase.co/functions/v1/refresh_feeds \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json"
